### PR TITLE
feat: update input fields styling

### PR DESCRIPTION
**Pull request by lessp**
- Updates FormInput to correspond to new style-guide
- Fixes broken tests

### CODE REVIEW

**Comment by sebastianandreasson** [comment]
Looks great! only thing is that the `npm run coverage` fails because of the two new components `FormError` and `ForInputUnderline`. Since it's running in the travis-ci maybe we should just add those even if it's super simple components..?

**Comment by lessp** [comment]
> Looks great! only thing is that the `npm run coverage` fails because of the two new components `FormError` and `ForInputUnderline`. Since it's running in the travis-ci maybe we should just add those even if it's super simple components..?

Ah! They're old, and no longer used with the current FormInput, but perhaps I could just add tests for "legacy-ish" reasons?

**Comment by sebastianandreasson** [comment]
In that case I suggest just deleting them and then the coverage test will also pass, since we're doing a major release here it should be fine.

**Comment by lessp** [comment]
> In that case I suggest just deleting them and then the coverage test will also pass, since we're doing a major release here it should be fine.

Said and done!

**Pull request merged**
